  apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: census-rm-toolbox
    labels:
      app: census-rm-toolbox
      env: dev
  spec:
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        name: census-rm-toolbox
        labels:
          app: census-rm-toolbox
          env: dev
      spec:
        containers:
        - name: census-rm-toolbox
          image: eu.gcr.io/census-rm-ci/rm/census-rm-toolbox:latest
          tty: true
          stdin: true
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
          - name: gcp-credentials-volume
            mountPath: /gcp-credentials
          - name: cloud-sql-certs
            mountPath: "/root/.postgresql-rw"
            readOnly: true
          - name: read-replica-cloud-sql-certs
            mountPath: "/root/.postgresql"
            readOnly: true
          env:
          - name: RABBITMQ_SERVICE_HOST
            value: "rabbitmq"
          - name: RABBITMQ_SERVICE_PORT
            value: "5672"
          - name: RABBITMQ_HTTP_PORT
            value: "15672"
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-password
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/gcp-credentials/service-account-key.json"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: DB_HOST_RW
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: db-host
          - name: DB_PORT_RW
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: db-port
          - name: DB_NAME_RW
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: db-name
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-read-replica-config
                key: db-host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: db-read-replica-config
                key: db-port
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-read-replica-config
                key: db-name
          - name: PROJECT_NAME
            valueFrom:
              configMapKeyRef:
                name: project-config
                key: project-name
        volumes:
        - name: gcp-credentials-volume
          secret:
            secretName: toolbox-credentials
        - name: cloud-sql-certs
          secret:
            secretName: cloud-sql-certs
            defaultMode: 0400
            items:
            - key: "root.crt"
              path: "root.crt"
            - key: "postgresql.crt"
              path: "postgresql.crt"
            - key: "postgresql.key"
              path: "postgresql.key"
        - name: read-replica-cloud-sql-certs
          secret:
            secretName: read-replica-cloud-sql-certs
            defaultMode: 0400
            items:
            - key: "root.crt"
              path: "root.crt"
            - key: "postgresql.crt"
              path: "postgresql.crt"
            - key: "postgresql.key"
              path: "postgresql.key"

